config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  resources :tracks, only: [:index, :show, :update, :create, :new, :destroy]
  resource :player, only: [:show, :create, :destroy]
  get '/square-player/:id', to: 'players#iframe', as: "iframe"
  get '/auth/:provider/callback', to: 'sessions#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :user
  has_many :tracks
end

app/models/site.rb
class Site < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/track.rb
class Track < ApplicationRecord
  has_one_attached :cover_image
  has_one_attached :full_audio
  belongs_to :player
end

app/models/user.rb
class User < ApplicationRecord
  has_one :player
  has_many :sites
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def require_auth
    # redirect_to root_path unless session[:auth] || Rails.env.development?
    if Rails.env.development?
      mock_session_for_dev unless session[:user]
    else
      redirect_to root_path unless session[:auth]
    end
  end

  def square_client
    square_api_client = Square::SquareApiClient.new
      #   # THIS IS A PATCH UNTIL I FIGURE SOMETHING ELSE OUT TO MOCK TOKEN/OAUTH IN DEVELOPMENT ENVIRONMENT
    square_api_client.access_token = 
    Rails.env.development? ? 
    Rails.application.credentials.dig(:square, :square_access_token)    
    :
    session[:auth]['credentials']['token']
    # ^^^^^^^^^
    return square_api_client
  end

  def mock_session_for_dev
    sites = square_client.list_sites
      
    @local_sites = sites.map { |site| Site.find_or_create_by(site_id: site[:id], domain: site[:domain]) }
    @user = @local_sites.first.user
    unless @user
      @user = User.create
      player = @user.create_player
      @local_sites.each { |site| site.update(user_id: @user.id) }
    end
    session[:user] = @user
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :require_auth, except: [:iframe]

  def show
    @tracks = Player.first.tracks
    @custom_tracks = Player.find_by(user_id: session[:user]["id"]).tracks

    user_sites = square_client.list_sites
    if user_sites
      @sites = user_sites.map do |site| 
        snippet = square_client.get_snippet(site.id)
        { site: site, snippet: snippet}
      end
    end
  end

  def iframe
    @tracks = Player.find(params[:id]).tracks
    render inline: '<%= render "players/iframe" %>', layout: 'layouts/slim'
  end

  def create
    square_client.upsert_snippet(params[:format], content(params[:player]))
    redirect_to player_path
  end

  def destroy
    square_client.delete_snippet params[:format]
    redirect_to player_path
  end

private
  def content(id)
    render_to_string(partial: 'players/inject', locals: {player_id: id})
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # If you're using a strategy that POSTs during callback, you'll need to skip the authenticity token check for the callback action only. 
  skip_before_action :verify_authenticity_token, only: :create

  def create
    session[:auth] = auth_hash
    sites = square_client.list_sites
      #   # THIS IS A PATCH UNTIL I FIGURE SOMETHING ELSE OUT TO MOCK TOKEN/OAUTH IN DEVELOPMENT ENVIRONMENT 
    @local_sites = sites.map { |site| Site.find_or_create_by(site_id: site[:id], domain: site[:domain]) }
    @user = @local_sites.first.user
    unless @user
      @user = User.create
      player = @user.create_player
      @local_sites.each { |site| site.update(user_id: @user.id) }
    end
    # ^^^^^^^^^
    session[:user] = @user

    redirect_to player_path
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :set_track, only: [:show, :update]
  before_action :require_auth

  def index
    @tracks = Player.find_by(user_id: session[:user]["id"]).tracks
  end

  def show
  end

  def new
    @track = Track.new
  end

  def create
    @player = Player.find_by(user_id: session[:user]["id"])
    @track = Track.new(track_params.merge({player_id: @player.id}))
    if @track.save
      redirect_to @track
    else
      redirect_to welcome_path(track.id)
    end
  end

  def destroy
    Track.destroy(params[:id])
    redirect_to tracks_path
  end
  
  def update
    respond_to do |format|
      if @track.update(track_params)
        format.html { redirect_to @track, notice: 'track was successfully updated.' }
        format.json { render :show, status: :ok, location: @track }
      else
        format.html { render :index }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

private
  def track_params
    params.require(:track).permit(:title, :position, :artist, :cover_image, :full_audio, :link, :link_title)
  end

  def set_track
    @track = Track.find_by(id: params[:id])
    redirect_to root_path unless @track
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :require_auth, except: [:index]
  
  def index
    @tracks = Player.first.tracks
    render 'index', layout: 'landing'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-color-mode="light" data-light-theme="light">
  <head>
    <title>SquarePlayerApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&family=Quantico:wght@400;700&display=swap" rel="stylesheet">
  </head>
  <body>
    <div class="Layout">
      <div class="Layout-main">
        <%= yield %>
      </div>  
      <div class="Layout-sidebar">
        <div class="Header" id="Header__custom" >
          <div class="Header-item">
            <a href="#" class="Header-link f4 d-flex flex-items-center">
              <%= image_tag( "square_player_logo.png", size: '40x40')%>
              <span class="Header__title">square player</span>
            </a>
          </div>
        </div>
        <aside class="bg-gray-light p-3" style="max-width: 360px">
          <h5 class="text-gray mb-2 pb-1 border-bottom h-branded-font">Menu</h5>
          <nav class="SideNav">
            <%= link_to "Link", player_path, class: 'SideNav-subItem h-branded-font'%>
            <%= link_to "Customize", tracks_path, class: 'SideNav-subItem h-branded-font'%>
          </nav>
        </aside>
      </div>
    </div>
  </body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html data-color-mode="light" data-light-theme="light">
  <head>
    <title>SquarePlayerApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&family=Quantico:wght@400;700&display=swap" rel="stylesheet">
  </head>
  <body>
    <div class="Header" id="Header__custom" >
      <div class="Header-item Header-item--full">
        <a href="#" class="Header-link f4 d-flex flex-items-center">
          <%= image_tag( "square_player_logo.png", size: '40x40')%>
          <span class="Header__title">square player</span>
        </a>
      </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/layouts/slim.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SquarePlayerApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&family=Quantico:wght@400;700&display=swap" rel="stylesheet">
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/players/_iframe.html.erb
<div class="h-border-radius color-shadow-large ">
  <%= render(AudioPlayer::AudioPlayerComponent.new(tracks: @tracks))%>
</div>

app/views/players/_inject.html.erb
<script type="text/javascript">
  document.addEventListener("DOMContentLoaded", ready);
  function ready() {
    let ifrm = document.createElement("iframe");
    ifrm.setAttribute("src", "https://morning-hamlet-04857.herokuapp.com/square-player/<%=player_id%>");
    ifrm.style.position = "fixed";
    ifrm.style.zIndex = 100;
    ifrm.style.bottom = '15px';
    ifrm.style.right = 0;
    ifrm.style.height = "100px";
    ifrm.style.width = "100%";
    ifrm.style.maxWidth = "600px";
    ifrm.style.minWidth = "300px";
    ifrm.style.borderRadius = "25px";
    ifrm.style.background = "transparent";
    ifrm.style.border = "none";
    ifrm.style.scrolling = "no";
    ifrm.style.overflow = "hide";
    document.body.appendChild(ifrm);
  }
</script>

app/views/players/_new_player_form.html.erb
<div>
  <a target="_blank" href="https://<%=site[:site].domain%>"  class="f3-mktg"><%=site[:site].domain%></a>
</div>
<%= form_with(url: player_path(site[:site].id), method: :create) do |form|  %> 
  <div class="pt-5 d-flex flex-row flex-justify-start flex-items-center">
    <div class="ml-5">
      <%= form.radio_button :player, sample_player_id, checked: true %>
      <%= form.label :sample, "Sample Player" %>
    </div>
    <div class="ml-5">
      <%= form.radio_button :player, custom_player_id %>
      <%= form.label :custom, "Custom Player" %>
    </div>
    <div class="ml-5">
      <%= form.submit "Update", class: "btn-mktg btn-enterprise-mktg mr-3" %>
    </div>
  </div>
<% end %>

app/views/players/_remove_player_form.html.erb
<div class="d-flex flex-row flex-justify-start flex-items-center">
  <div class="pr-5">
    <a target="_blank" href="https://<%=site[:site].domain%>"  class="f3-mktg"><%=site[:site].domain%></a>
  </div>
  <%= button_to "Remove Player from Site", player_path(site[:snippet].site_id), :class => 'remove-cursor', :method => :delete, class: "btn-mktg btn-enterprise-mktg btn-sm-mktg" %>
</div>

app/views/players/show.html.erb
<div class="Hero-Header pb-10">
  <div class="mt-3 mb-1">
    <h1 class="h3-mktg h-branded-font mb-2">Link Square Player</h1>
    <p class="f3-mktg">
      Below you will find previews for both your custom player and a sample player for testing purposes. Add either one to your site by using the toggle select and then clicking on the "Add Player" button.
    </p>
    <hr width="100px"> 
  </div>
  <div class="h-Content-Container mt-5">
    <h5 class="h6-mktg">
      Preview Your Custom Player
    </h5>
    <div class="h-border-radius color-shadow-large mt-5">
      <%= render(AudioPlayer::AudioPlayerComponent.new(tracks: @tracks))%>
    </div>
  </div>
  <div class="h-Content-Container mt-5">
    <h5 class="h6-mktg">
      Sample Player For Testing
    </h5>
    <div class="h-border-radius color-shadow-large mt-5">
      <%= render(AudioPlayer::AudioPlayerComponent.new(tracks: @custom_tracks))%>
    </div>
  </div>
  <div class="h-Content-Container mt-5">
    <h5 class="h6-mktg">
      Add Player to Your Square Sites
    </h5>
  </div>
  <div class="mt-5">
    <% @sites.each do |site| %>
        <% if site[:snippet] %> 
          <%=render "remove_player_form", site: site, custom_player_id:  @custom_tracks.first.player_id, sample_player_id: @tracks.first.player_id %>
        <% else %>
          <%=render "new_player_form", site: site, custom_player_id:  @custom_tracks.first.player_id, sample_player_id: @tracks.first.player_id %>
        <% end %>
    <% end %>
  </div>
</div>

app/views/tracks/_form.html.erb
<%= form_with(model: @track, url: url, method: method) do |form|  %>
  <div class="d-flex flex-column form-group">
    <h6 class="h6-mktg h-branded-font mb-5">Track Details</h6>  
    <div class="form-group-header">
      <%= form.label :title, "Track Title" %>
    </div>
    <div class="form-group-body mb-3">
      <%= form.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group-header">
      <%= form.label :title, "Track Link" %>
    </div>
    <div class="form-group-body mb-3">
      <%= form.text_field :link, class: "form-control"%>
    </div>
    <div class="form-group-header">  
      <%= form.label :title, "Link Text" %>
    </div>
    <div class="form-group-body mb-3">
      <%= form.text_field :link_title, class: "form-control"%>
    </div>
      <div class="form-group-header">
        <%= form.label :artist, "Artist" %>
      </div>
      <div class="form-group-body mb-3">
      <%= form.text_field :artist, class: "form-control"%>
    </div>
      <div class="form-group-header">
        <%= form.label :cover_image, "Update Track Cover Image" %>
      </div>
      <div class="form-group-body mb-3">
      <%= form.file_field :cover_image %>
      </div>
      <div class="form-group-header">
        <%= form.label :full_audio, "Update Track Audio" %>
      </div>
      <div class="form-group-body mb-3">
      <%= form.file_field :full_audio %>
      </div>
      <div class="pt-4 pb-5">
        <%= form.submit "Update", class: "btn-mktg btn-enterprise-mktg mr-3" %>
      </div>
  </div>
<% end %>

app/views/tracks/index.html.erb
<div class="Hero-Header">
  <div class="mt-3 mb-1">
    <h1 class="h3-mktg h-branded-font mb-2">Square Player Tracks</h1>
    <p class="f3-mktg">
      Here is a list of the custom tracks you have uploaded to include in your Square Player
    </p>
    <%= link_to "Add New Track", new_track_path, class: "btn-mktg btn-enterprise-mktg btn-sm-mktg" %>
    <hr width="100px"> 
  </div>
  <div class="h-Content-Container mt-5">
    <div class="container-lg d-flex flex-column">
      <% @tracks.each do |track| %>
        <div class="h-w-max-800 border p-4 d-flex flex-row flex-justify-between">
          <div class="d-flex flex-row flex-justify-start flex-items-center">
            <%if track.cover_image.attached? %> 
              <%= image_tag track.cover_image, width:'60px', height:'60px'  %>
            <% end %>
              <div class="pl-5">
                <h4 class="h4-mktg h-branded-font"><%=track.title%></h4>
                <p class="f3-mktg"><%=track.artist%></p>
              </div>
          </div>
          <div class="">
            <%=link_to "View / Edit", track_path(track.id) %>
            <%=link_to 'Delete', track_path(track.id), method: :delete, data: { confirm: "Are you sure you want to remove this track from your player's library?" }, class: "pl-5"  %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/tracks/new.html.erb
<div class="container-lg d-flex flex-column flex-justify-start">
  <div class="mt-3 mb-1">
    <h1 class="h3-mktg h-branded-font mb-2">New Track</h1>
    <p class="f3-mktg">
      Add a new track to your player.
    </p>
    <hr width="100px"> 
  </div>
  <%=render "form", method: "post", url: tracks_path %>
</div>

app/views/tracks/show.html.erb
<div class="container-lg d-flex flex-column flex-justify-start">
  <div class="mt-3 mb-1">
    <h1 class="h3-mktg h-branded-font mb-2">View/Edit Track</h1>
    <p class="f3-mktg">
      Here are your track details. You can also scroll to the bottom of the page to view a sample player with your track details.
    </p>
    <hr width="100px"> 
  </div>

  <%=render "form", method: "patch", url: track_path(@track) %>
  <hr width="100px">     
  <%if @track.full_audio.attached? && @track.cover_image.attached? %>
    <div class="pb-10  d-flex flex-column flex-justify-start">
      <h6 class="h6-mktg h-branded-font mb-5">Current Track Preview</h6>  
      <div class="h-border-radius color-shadow-large p-2">
        <%= render(AudioPlayer::AudioPlayerComponent.new(tracks: [@track]))%>
      </div>
    </div>
  <%end%>
</div>

app/views/welcome/index.html.erb
<div class="Hero-Component">
  <div class="pl-5 pt-5">
    <h1 class="h0-mktg h-branded-font">Boost sales</h1>
    <h1 class="h0-mktg h-branded-font">with  your sounds</h1>
    <div class="f1-mktg  pt-5">
      Play your creations on your square site
    </div>
    <div class="f1-mktg">
      with a personalized audio player.
    </div>
    <div class="pl-3 pt-5 Hero-Component__cta-container ">
      <p>
        <a  href="/auth/square" class="btn-mktg btn-enterprise-mktg" type="button">Sign Up with Square</a>
        <span>Free for Square Sites !</span>
      </p>
    </div>
  </div>
  <div class="p-0 m-0 h-w-100 h-fixed-bottom">
    <%= render 'players/iframe' %>
  </div>
</div>